DROP SEQUENCE USER_SEQ;
DROP TABLE USER_AUTH;
DROP SEQUENCE EXPERT_SEQ;
DROP TABLE EXPERT_LOCATION;
DROP SEQUENCE EXPERT_LOCATION_SEQ;
DROP TABLE EXPERT_LICENSE;
DROP SEQUENCE EXPERT_LICENSE_SEQ;
DROP SEQUENCE CATEGORY_SEQ;
DROP TABLE EXPERT_CATEGORY;
DROP TABLE EXPERT;
DROP TABLE CATEGORY;
DROP TABLE USERS;

-- USERS 테이블
CREATE TABLE USERS (
    id NUMBER PRIMARY KEY,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255),
    nickname VARCHAR2(50) NOT NULL,
    profile_img VARCHAR2(255),
    provider VARCHAR2(30),
    provider_id VARCHAR2(100),
    enabled CHAR(1) DEFAULT 'Y',
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE,
    is_deleted CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- USER_AUTHORITIES 테이블
CREATE TABLE USER_AUTH (
    user_id NUMBER REFERENCES USERS(id),
    authority VARCHAR2(20) NOT NULL,
    PRIMARY KEY (user_id, authority)
);

-- EXPERT_PROFILE 테이블
CREATE TABLE EXPERT (
    id NUMBER PRIMARY KEY,
    user_id NUMBER UNIQUE NOT NULL REFERENCES USERS(id),
    career CLOB,
    profile_img VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'PENDING',
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE,
    reviewed_at DATE
);

CREATE SEQUENCE EXPERT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- EXPERT_LOCATION 테이블
CREATE TABLE EXPERT_LOCATION (
    id NUMBER PRIMARY KEY,
    expert_id NUMBER NOT NULL REFERENCES EXPERT(id),
    city VARCHAR2(255) NOT NULL,
    district VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE EXPERT_LOCATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- EXPERT_LICENSE 테이블
CREATE TABLE EXPERT_LICENSE (
    id NUMBER PRIMARY KEY,
    expert_id NUMBER NOT NULL REFERENCES EXPERT(id),
    image_path VARCHAR2(255) NOT NULL,
    uploaded_at DATE DEFAULT SYSDATE
);

CREATE SEQUENCE EXPERT_LICENSE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- CATEGORY 테이블
CREATE TABLE CATEGORY (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL
);

CREATE SEQUENCE CATEGORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- EXPERT_CATEGORY 테이블
CREATE TABLE EXPERT_CATEGORY (
    expert_id NUMBER NOT NULL REFERENCES EXPERT(id),
    category_id NUMBER NOT NULL REFERENCES CATEGORY(id),
    PRIMARY KEY (expert_id, category_id)
);
